# Generated by Django 2.0.2 on 2018-03-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comicId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comic')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='newest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newest', to='comic.Episode'),
        ),
        migrations.AddField(
            model_name='comic',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='comic.Episode'),
        ),
    ]
