# Generated by Django 2.0.2 on 2018-03-02 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20180301_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 3, 15, 0, 75582)),
        ),
    ]
