# Generated by Django 2.0.2 on 2018-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_comic_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='updateTime',
            field=models.DateTimeField(),
        ),
    ]
